name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: dependences
      run: |
        sudo apt-get update
        sudo apt-get -y install gcc-mingw-w64-x86-64
        sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
        sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
        go get
        rice embed-go
        
    - name: Build-liunx_amd64
      run: |
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o GoPan_liunx_amd64
        strip -s GoPan_liunx_amd64
    - name: Build-liunx_arm64
      run: |
        GOOS=linux GOARCH=arm64 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ go build -o GoPan_liunx_arm64
        aarch64-linux-gnu-strip -s GoPan_liunx_arm64
        
    - name: Build-liunx_arm
      run: |
        GOOS=linux GOARCH=arm CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc  CXX=arm-linux-gnueabihf-g++ go build -o GoPan_liunx_arm 
        arm-linux-gnueabihf-strip -s GoPan_liunx_arm
    - name: Build-windows_amd64
      run: |
        GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -o GoPan_windows_amd64.exe
        x86_64-w64-mingw32-strip -s GoPan_windows_amd64.exe
        
    - name: Upload binary files (liunx_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-liunx_amd64
        path: GoPan_liunx_amd64

    - name: Upload binary files (liunx_arm64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-liunx_arm64
        path: GoPan_liunx_arm64
        
    - name: Upload binary files (liunx_arm)
      uses: actions/upload-artifact@v2
      with:
        name: Build-liunx_arm
        path: GoPan_liunx_arm

    - name: Upload binary files (windows_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: Build-windows_amd64
        path: GoPan_windows_amd64.exe
